public class myadditions {
public Integer x = 20;
public Integer y = 10;
public Integer z;
public Integer d;
public Integer m;
public Integer s;    
    public void myAdd(){
        z =x+y;
        system.debug('The value of z is---->'+z);
    }
        public void mySub(){
        d =x-y;
        system.debug('The value of D is---->'+d);
    }
        public void myMul(){
        m =x*y;
        system.debug('The value of M is---->'+m);
    }
            public void myDiv(){
        s =x/y;
        system.debug('The value of S is---->'+s);
    }
}